org.gradle.jvmargs=-Xmx64G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true


minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neoforge_version=21.1.220
forge_version_range=[21,)
loader_version_range=[4,)

mod_id=battle_arts
display_name=Epic Fight - Battle Arts
license=MIT
group_id=net.forixaim
authors=Forixaim
issue_tracker=https://github.com/Forixaim/Battle-Arts/issues
source_code=https://github.com/Forixaim/Battle-Arts
display_url=https://github.com/Forixaim/Battle-Arts
credits="Me"
description= Go read the main page of this mod on CurseForge.
