modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
logoFile = "battle_arts_title.png"


description='''${mod_description}'''

[[dependencies."${mod_id}"]]
   modId="forge"
   mandatory=true
   versionRange="${forge_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId="minecraft"
   mandatory=true
   versionRange="${minecraft_version_range}"
   ordering="NONE"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId="epicfight"
   mandatory=true
   versionRange="[20.14.,20.15)"
   ordering="AFTER"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId="battlearts_api"
   mandatory=true
   versionRange="[20.14, 20.15)"
   ordering="AFTER"
   side="BOTH"

[[dependencies."${mod_id}"]]
   modId = "epicfightx"
   mandatory = false
   versionRange = "INCOMPATIBLE"
   ordering = "NONE"
   side = "BOTH"


