modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Forixaim/Epic-Fight-Battle-Arts/issues"
[[mods]] #mandatory
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
logoFile="battle_arts_title.png"
credits="The Epic Fight Team"
authors="${mod_authors}" #optional

description='''${mod_description}'''
[[dependencies."${mod_id}"]]
   modId="epicfight"
   mandatory=true
   versionRange="[21.16,)"
   ordering="AFTER"
   side="BOTH"
[[dependencies."${mod_id}"]]
   modId = "neoforge"
   type = "required"
   versionRange = "[21,)"
   ordering = "NONE"
   side = "BOTH"
[[dependencies."${mod_id}"]]
   modId = "minecraft"
   type = "required"
   versionRange = "${minecraft_version_range}"
   ordering = "NONE"
   side = "BOTH"

[[accessTransformers]]
   file="META-INF/accesstransformer.cfg"
